name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Setup ğŸ”§
        run: |
          sudo .local/bin/setup

      - name: Build (web) ğŸ”¨
        run: |
          .local/bin/build

      - name: Build (pdf) ğŸ”¨
        uses: docker://pandoc/latex:2.14.1
        with:
          entrypoint: /bin/sh
          args: .local/bin/build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .local/srv
