name: Publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup
        run: |
          sudo .local/bin/bootstrap

      - name: Web
        run: |
          .local/bin/web tmp

      - name: Pdf
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/sh
          args: .local/bin/pdf tmp

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: tmp
          clean: true
